# Generated by Django 2.0.6 on 2018-07-11 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180702_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='next_of_kin',
            field=models.ManyToManyField(related_name='_user_next_of_kin_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
