# Generated by Django 2.0.6 on 2018-06-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
