# Generated by Django 2.0.6 on 2018-06-24 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180624_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextofkin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='next_of_kin',
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='next_of_kin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
