# Generated by Django 2.0.6 on 2018-06-24 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180624_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextofkin',
            name='next_of_kin',
            field=models.ManyToManyField(related_name='next_of_kins', to=settings.AUTH_USER_MODEL),
        ),
    ]
