# Generated by Django 2.0.6 on 2018-06-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180624_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextofkin',
            name='user',
        ),
    ]
