# Generated by Django 2.0.6 on 2018-06-24 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_nextofkin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nextofkin',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='next_of_kin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NextOfKin',
        ),
    ]
