# Generated by Django 2.0.6 on 2018-06-24 15:44

from django.conf import settings
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180624_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='alternative_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_of_kin',
            field=models.ManyToManyField(related_name='next_of_kins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='primary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
