# Generated by Django 2.0.6 on 2018-06-24 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180624_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='related_to',
        ),
        migrations.AddField(
            model_name='user',
            name='next_of_kin',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
