# Generated by Django 2.0.6 on 2018-06-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180624_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='patient',
        ),
    ]
