# Generated by Django 2.0.6 on 2018-06-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_user_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superuser',
        ),
    ]
