# Generated by Django 2.0.6 on 2018-06-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
    ]
