# Generated by Django 2.0.6 on 2018-06-25 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='next_of_kin',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
