# Generated by Django 2.0.6 on 2018-06-24 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departmentpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpatient',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='departments.Department'),
        ),
        migrations.AlterField(
            model_name='departmentpatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to=settings.AUTH_USER_MODEL),
        ),
    ]
