# Generated by Django 2.0.6 on 2018-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20180624_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpatient',
            name='discharged',
            field=models.BooleanField(default=False),
        ),
    ]
