# Generated by Django 2.0.6 on 2018-06-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_auto_20180624_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='patient',
        ),
    ]
