# Generated by Django 2.0.6 on 2018-06-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0011_auto_20180624_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='user',
        ),
    ]
