# Generated by Django 2.0.6 on 2018-06-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_auto_20180625_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deleted',
        ),
    ]
