# Generated by Django 2.0.6 on 2018-06-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='county',
        ),
        migrations.RemoveField(
            model_name='location',
            name='subcounty',
        ),
        migrations.RemoveField(
            model_name='location',
            name='village',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ward',
        ),
    ]
