# Generated by Django 2.0.6 on 2018-06-24 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20180624_1008'),
        ('users', '0004_auto_20180624_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
