# Generated by Django 2.0.6 on 2018-06-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcounty',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='locations.County'),
        ),
    ]
