# Generated by Django 2.0.6 on 2018-06-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20180624_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='locations.Ward'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='subcounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='locations.Subcounty'),
        ),
    ]
