# Generated by Django 2.0.6 on 2018-06-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20180624_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ward',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
