# Generated by Django 2.0.6 on 2018-06-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20180625_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='subcounty',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='village',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='deleted',
        ),
    ]
