# Generated by Django 2.0.6 on 2018-06-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20180625_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='village',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
